name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

- name: Code Climate Coverage Action
  uses: paambaati/codeclimate-action@v2.3.0
  with:
    # Coverage command to execute
    coverageCommand: # optional, default is yarn coverage
    # Enable debugging logs for the Code Climate test reporter
    debug: # optional, default is false
